[project]
name = 'Decentralized-Invasive-Species-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sighting-report]
path = 'contracts/sighting-report.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-identification]
path = 'contracts/species-identification.clar'
clarity_version = 2
epoch = 2.5

[contracts.treatment-verification]
path = 'contracts/treatment-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
